-- Script para criar a tabela de relatórios
CREATE TABLE IF NOT EXISTS tabela_relatorios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id TEXT NOT NULL,
    aba TEXT NOT NULL,
    dados_relatorio JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(process_id, aba)
);

-- Criar um índice para otimizar as buscas por processo e aba
CREATE INDEX IF NOT EXISTS idx_tabela_relatorios_process_id_aba ON tabela_relatorios (process_id, aba);

-- Se precisar permitir anonimo para Inserção/Atualização via REST (ajuste conforme as políticas de segurança do seu banco):
ALTER TABLE tabela_relatorios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable ALL for anon on tabela_relatorios" 
ON tabela_relatorios 
FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);
