-- Script para criar a tabela de deliberações
CREATE TABLE IF NOT EXISTS tabela_deliberacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id TEXT NOT NULL,
    perfil TEXT NOT NULL,          -- Ex: 'CHEFIA_SPU', 'COORDENACAO_SPU', 'SUPERINTENDENCIA'
    dados_deliberacao JSONB NOT NULL, -- Guardará o objeto completo da decisão e motivos
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para busca rápida pelo processo e perfil
CREATE INDEX IF NOT EXISTS idx_delib_process_perfil ON tabela_deliberacoes (process_id, perfil);

-- Habilita RLS para acesso anônimo via API Rest (padrão do projeto para testes)
ALTER TABLE tabela_deliberacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable ALL for anon on tabela_deliberacoes" 
ON tabela_deliberacoes 
FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);
