import re
html = open('foco-03.html', encoding='utf-8').read()

replacements = {
    'opo': 'opção',
    'opo': 'opção',
    'Regularizao': 'Regularização',
    'Fundiria': 'Fundiária',
    'Desestatizao': 'Desestatização',
    'Privatizao': 'Privatização',
    'estratgia': 'estratégia',
    'estratgica': 'estratégica',
    'observaes': 'observações',
    'Observaes': 'Observações',
    'vinculao': 'vinculação',
    'Polticas': 'Políticas',
    'Pblicas': 'Públicas',
    'pblicas': 'públicas',
    'destinao': 'destinação',
    's quais': 'às quais',
    'Habitao': 'Habitação',
    'Segurana': 'Segurança',
    'Pblica': 'Pública',
    'Sade': 'Saúde',
    'Educao': 'Educação',
    'beneficirios': 'beneficiários',
    'urbanstica': 'urbanística',
    'Compatvel': 'Compatível',
    'incompatvel': 'incompatível',
    'Incompatvel': 'Incompatível',
    'restries': 'restrições',
    'aprovao': 'aprovação',
    'especfica': 'específica',
    'contrrio': 'contrário',
    'No foi possvel': 'Não foi possível',
    'ausncia': 'ausência',
    'informaes': 'informações',
    'Informaes': 'Informações',
    'condies': 'condições',
    'modificao': 'modificação',
    'Modificao': 'Modificação',
    'edificao': 'edificação',
    'fscas': 'físicas',
    'fsicas': 'físicas',
    'H': 'Há',
    '': 'á',  # fallback general but risky, better specify words
    'vinculao': 'vinculação',
    'Polticas': 'Políticas',
    'Pblicas': 'Públicas',
    'No': 'Não',
    'Sem informao': 'Sem informação',
    'informaes': 'informações',
    'Informaes': 'Informações',
    'avaliao': 'avaliação',
    'Avaliao': 'Avaliação',
    'populao': 'população',
    'no': 'não',
    'slidos': 'sólidos',
    'aquicultura': 'aquicultura',
    'pesquisa e extenso': 'pesquisa e extensão',
    'sade': 'saúde',
    'segurana': 'segurança',
    'fundao': 'fundação',
    'habitao': 'habitação',
    'produo': 'produção',
    'recreao': 'recreação',
    'durao': 'duração',
    'prestao': 'prestação',
    'requalificao': 'requalificação',
    'originrios': 'originários',
    'atuao': 'atuação',
    'instituio': 'instituição',
    'locao': 'locação',
    'Concesso': 'Concessão',
    'Direito de Superfcie': 'Direito de Superfície',
    'Doao': 'Doação',
    'Inscrio de ocupao': 'Inscrição de ocupação',
    'Permisso de uso': 'Permissão de uso',
    'autorizao': 'autorização',
    'Autorizao': 'Autorização',
    'destinaes': 'destinações',
    'Dao em pagamento': 'Dação em pagamento',
    'Declarao': 'Declaração',
    'Integralizao': 'Integralização',
    'Imobilirio': 'Imobiliário',
    'imobilirio': 'imobiliário',
    'especfico': 'específico',
    'Especfico': 'Específico',
    'agrcola': 'agrícola',
    'pecuria': 'pecuária',
    'conservao': 'conservação',
    'preservao': 'preservação',
    'metr': 'metrô',
    'porturia': 'portuária',
    'ferroviria': 'ferroviária',
    'aerdromo': 'aeródromo',
    'residncia': 'residência',
    'presdio': 'presídio',
    'custdia': 'custódia',
    'cemiterio': 'cemitério',
    'espao': 'espaço',
    'servio': 'serviço',
    'Servio': 'Serviço',
    'servios': 'serviços',
    'socioassistencial': 'socioassistencial',
    'pblica': 'pública',
    'Pblica': 'Pública',
    'pblicas': 'públicas',
    'Pblicas': 'Públicas',
    'pblico': 'público',
    'Pblico': 'Público',
    'pblicos': 'públicos',
    'Pblicos': 'Públicos',
    'indgena': 'indígena',
    'territrio': 'território',
    'bsica': 'básica',
    'laboratrio': 'laboratório',
    'filantrpica': 'filantrópica',
    'cidado': 'cidadão',
    'cidadania': 'cidadania',
    'assistncia': 'assistência',
    'extrativistas': 'extrativistas',
    'comercio': 'comércio',
    'atacadista': 'atacadista',
    'varejista': 'varejista',
    'gs': 'gás',
    'eltrica': 'elétrica',
    'sanitrio': 'sanitário',
    'gua': 'água',
    'rea': 'área',
    'reas': 'áreas',
    'estdio': 'estádio',
    'ginsio': 'ginásio',
    'orgo': 'órgão',
    'rgo': 'órgão',
    'diplomatica': 'diplomática',
    'consular': 'consular',
    'Acordo de Coopera??o T?cnica': 'Acordo de Cooperação Técnica',
    'Regulariza??o Fundi?ria Urbana': 'Regularização Fundiária Urbana',
    'Afeta??o': 'Afetação',
    'Autoriza??o': 'Autorização',
    'sustent?vel': 'sustentável',
    'Cess?o': 'Cessão',
    'provis?ria': 'provisória',
    'Provis?ria': 'Provisória',
    'Concess?o': 'Concessão',
    'Superf?cie': 'Superfície',
    'Da??o': 'Dação',
    'Declara??o': 'Declaração',
    'Servi?o': 'Serviço',
    'P?blico': 'Público',
    'Doa??o': 'Doação',
    'Inscri??o': 'Inscrição',
    'ocupa??o': 'ocupação',
    'Integraliza??o': 'Integralização',
    'Imobili?rio': 'Imobiliário',
    'Loca??o': 'Locação',
    'Permiss?o': 'Permissão',
    'dura??o': 'duração',
}

# Realizar substituies cuidadosamente
for k, v in replacements.items():
    html = html.replace(k, v)

with open('foco-03.html', 'w', encoding='utf-8') as f:
    f.write(html)
print("Substituies extras concludas.")
