-- Script para criar as novas tabelas de Origem e Definitiva no Supabase

-- 1. Criação da Tabela de Origem (Simula as APIs e sistemas externos)
CREATE TABLE IF NOT EXISTS foco_origem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id TEXT UNIQUE NOT NULL,
    form_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Criação da Tabela Definitiva (Onde os dados são salvos após a confirmação)
CREATE TABLE IF NOT EXISTS foco_final (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id TEXT UNIQUE NOT NULL,
    form_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Opcional: Criar a foco_drafts caso ela tenha sido apagada (ela já deve existir no seu banco)
CREATE TABLE IF NOT EXISTS foco_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id TEXT UNIQUE NOT NULL,
    form_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
