-- Script de Criação do Banco de Dados Foco-11 no Supabase
-- Arquitetura: Modelo Híbrido (Relacional para Chaves + JSONB para Dados Livres)

-- 1. TABELA PRINCIPAL: REQUERIMENTOS
-- Esta é a tabela mãe. Nenhum dado de fluxo ou decisão existe sem um requerimento.
CREATE TABLE IF NOT EXISTS tabela_requerimentos (
    numero_requerimento TEXT PRIMARY KEY, -- Identificador único (ex: PR2026001)
    dados_json JSONB NOT NULL DEFAULT '{}'::jsonb, -- Campos livres do formulário (uf, município, interessado, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. TABELA DE IMÓVEIS: SPU
-- Dados físicos e cadastrais do imóvel. Existe independentemente do requerimento.
CREATE TABLE IF NOT EXISTS tabela_spu (
    numero_rip TEXT PRIMARY KEY, -- Identificador único do imóvel no sistema SPU
    dados_json JSONB NOT NULL DEFAULT '{}'::jsonb, -- Campos livres (área, vocação, endereço, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. TABELA DE ANÁLISES: FOCO
-- Contém os dados das análises feitas nas Abas do sistema. 
-- Um requerimento tem uma ficha de foco.
CREATE TABLE IF NOT EXISTS tabela_foco (
    numero_requerimento TEXT PRIMARY KEY REFERENCES tabela_requerimentos(numero_requerimento) ON DELETE CASCADE,
    dados_json JSONB NOT NULL DEFAULT '{}'::jsonb, -- Campos livres (decisões das abas, justificativas, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. TABELAS SATÉLITES DE HISTÓRICO (Fluxo, Decisões, Atribuições)
-- Como um requerimento pode ter VÁRIOS status, decisões ou atribuições ao longo do tempo,
-- elas precisam de um ID próprio (chave primária serial) e apontam para o requerimento (chave estrangeira).

-- 4.1 Histórico de Status do Fluxo
CREATE TABLE IF NOT EXISTS tabela_status_fluxo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_requerimento TEXT NOT NULL REFERENCES tabela_requerimentos(numero_requerimento) ON DELETE CASCADE,
    dados_json JSONB NOT NULL DEFAULT '{}'::jsonb, -- Campos livres (checkpoint, status_geral, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4.2 Histórico de Atribuições (Quem está cuidando do processo)
CREATE TABLE IF NOT EXISTS tabela_atribuicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_requerimento TEXT NOT NULL REFERENCES tabela_requerimentos(numero_requerimento) ON DELETE CASCADE,
    dados_json JSONB NOT NULL DEFAULT '{}'::jsonb, -- Campos livres (servidor, setor_responsável, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4.3 Histórico de Decisões Institucionais
CREATE TABLE IF NOT EXISTS tabela_decisao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_requerimento TEXT NOT NULL REFERENCES tabela_requerimentos(numero_requerimento) ON DELETE CASCADE,
    dados_json JSONB NOT NULL DEFAULT '{}'::jsonb, -- Campos livres (nome_instancia, parecer, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
